//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batnum.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Batnum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTER TAKES {0} AND LEAVES {1}.
        /// </summary>
        internal static string COMPTURN {
            get {
                return ResourceManager.GetString("COMPTURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTER TAKES {0} AND LOSES.
        /// </summary>
        internal static string END_COMPLOSE {
            get {
                return ResourceManager.GetString("END_COMPLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPUTER TAKES {0} AND WINS.
        /// </summary>
        internal static string END_COMPWIN {
            get {
                return ResourceManager.GetString("END_COMPWIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITS A DRAW, THERE ARE ONLY {0} PIECES LEFT.
        /// </summary>
        internal static string END_DRAW {
            get {
                return ResourceManager.GetString("END_DRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOUGH LUCK, YOU LOSE..
        /// </summary>
        internal static string END_PLAYERLOSE {
            get {
                return ResourceManager.GetString("END_PLAYERLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS, YOU WIN..
        /// </summary>
        internal static string END_PLAYERWIN {
            get {
                return ResourceManager.GetString("END_PLAYERWIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATNUM.
        /// </summary>
        internal static string GAME_NAME {
            get {
                return ResourceManager.GetString("GAME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILLEGAL MOVE, RENETER IT.
        /// </summary>
        internal static string INPUT_ILLEGAL {
            get {
                return ResourceManager.GetString("INPUT_ILLEGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR MOVE ?.
        /// </summary>
        internal static string INPUT_TURN {
            get {
                return ResourceManager.GetString("INPUT_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I TOLD YOU NOT TO USE ZERO! COMPUTER WINS BY FORFEIT..
        /// </summary>
        internal static string INPUT_ZERO {
            get {
                return ResourceManager.GetString("INPUT_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATIVE COMPUTING MORRISTOWN, NEW JERSEY.
        /// </summary>
        internal static string INTRO_HEADER {
            get {
                return ResourceManager.GetString("INTRO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS PROGRAM IS A &apos;BATTLE&apos; OF NUMBERS GAME, WHERE THE COMPUTER IS YOUR OPPONENT.
        /// </summary>
        internal static string INTRO_PART1 {
            get {
                return ResourceManager.GetString("INTRO_PART1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE GAME STARTS WITH AN ASSUMED PILE OF OBJECTS. YOU AND YOUR OPPONENT ALTERNATELY REMOVE OBJECTS FROM THE PILE. WINNNING IS DEFINED IN ADVANCE AS TAKING THE LAST OBJECT OR NOT. YOU CAN ALSO SPECIFY SOME OTHER BEGINING CONDITIONS. DON&apos;T USER ZERO, HOWWEVER, IN PLAYING THE GAME..
        /// </summary>
        internal static string INTRO_PART2 {
            get {
                return ResourceManager.GetString("INTRO_PART2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER MIN AND MAX ?.
        /// </summary>
        internal static string START_QUESTION_DRAWMINMAX {
            get {
                return ResourceManager.GetString("START_QUESTION_DRAWMINMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER PILE SIZE ?.
        /// </summary>
        internal static string START_QUESTION_PILESIZE {
            get {
                return ResourceManager.GetString("START_QUESTION_PILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER START OPTION - 1 COMPUTER FIRST, 2 YOU FIRST ?.
        /// </summary>
        internal static string START_QUESTION_WHOSTARTS {
            get {
                return ResourceManager.GetString("START_QUESTION_WHOSTARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER WIN OPTION - 1 TO TAKE LAST, 2 TO AVOID LAST: ?.
        /// </summary>
        internal static string START_QUESTION_WINOPTION {
            get {
                return ResourceManager.GetString("START_QUESTION_WINOPTION", resourceCulture);
            }
        }
    }
}
