#!/usr/bin/perl
use strict;

print ' 'x26 . "BUZZWORD GENERATOR\n";
print ' 'x15 . "CREATIVE COMPUTING MORRISTOWN, NEW JERSEY\n";
print "\n\n\n";

print "THIS PROGRAM PRINTS HIGHLY ACCEPTABLE PHRASES IN\n";
print "'EDUCATOR-SPEAK' THAT YOU CAN WORK INTO REPORTS\n";
print "AND SPEECHES. WHENEVER A QUESTION MARK IS PRINTED,\n";
print "TYPE A 'Y' FOR ANOTHER PHRASE OR 'N' TO QUIT.\n";
print "\n\n"; print "HERE'S THE FIRST PHRASE; ";

my @A= ("",
	"ABILITY","BASAL","BEHAVIORAL","CHILD-CENTERED",
	"DIFFERENTIATED","DISCOVERY","FLEXIBLE","HETEROGENEOUS",
	"HOMOGENEOUS","MANIPULATIVE","MODULAR","TAVISTOCK",
	"INDIVIDUALIZED","LEARNING","EVALUATIVE","OBJECTIVE", 
	"COGNITIVE","ENRICHMENT","SCHEDULING","HUMANISTIC",
	"INTEGRATED","NON-GRADED","TRAINING","VERTICAL AGE",
	"MOTIVATIONAL","CREATIVE","GROUPING","MODIFICATION",
	"ACCOUNTABILITY","PROCESS","CORE CURRICULUM","ALGORITHM",
	"PERFORMANCE","REINFORCEMENT","OPEN CLASSROOM","RESOURCE", 
	"STRUCTURE","FACILITY","ENVIRONMENT" 
	);

my $Y;
do {
	print $A[int(13*rand(1)+1)]." ";
	print $A[int(13*rand(1)+14)]." ";
	print $A[int(13*rand(1)+27)]; print "\n";
	print "? ";
	chomp ($Y = <STDIN>);
	} until ($Y ne "Y");

print "COME BACK WHEN YOU NEED HELP WITH ANOTHER REPORT!\n";
exit;


